version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5847:5847"
    restart: always
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "7485:7485"
    restart: always
    depends_on:
      - backend